name: Build FreeFireVIP dylib

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Theos
      run: |
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
        echo "THEOS=$(pwd)/theos" >> $GITHUB_ENV

    - name: Build
      run: |
        export THEOS=$(pwd)/theos
        make

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: FreeFireVIP-dylib
        path: .theos/obj/debug/*.dylib
